[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "edit trip nasty flight prize spot zebra private skate benefit diamond uncover confirm fault moment state angle reflect effort sphere joy jelly defy heart"
